import Head from 'next/head'
import Image from 'next/image'
import Door from '../components/door'
import Gift from '../components/Gift'


export default function Home() {
  return (
 <>
      <Head>
        <title>Doors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{display: 'flex'}}>
    <Door selectedDoor />
    <Door />
      </div>
 </>
)
}
