import Head from 'next/head'
import Card from '../components/Card'
import styles from '../styles/form.module.css'
import Link from 'next/link'



export default function Form() {

  return (
   
    <div className={styles.form}>
      <Head>
        <title>Doors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Card bgcolor="#c0392c" >
          <h1>Monty Hall</h1>
        </Card>
        <Card />
        

      </div>
      <div>
      <Card />
        <Card bgcolor="#28a085" >
          <Link href={`/game/4/2`} style={{textDecoration: 'none'}}>
            <h2 style={{display:"flex", flex: "1",justifyContent:"center", alignContent:"center", margin:"0", color:"white" }} >
              Iniciar

            </h2>
          </Link>
        </Card>

      </div>

    </div>
    
  )
}
