import Head from 'next/head'
import Card from '../components/Card'
import styles from '../styles/form.module.css'
import Link from 'next/link'
import NumberInput from '../components/NumberInput'
import { useState } from 'react'



export default function Form() {
  const [qtyDoors, setQtyDoors] = useState(3)
  const [gift, setGift] = useState(1)

  return (
   
    <div className={styles.form}>
      <Head>
        <title>Doors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Card bgcolor="#c0392c" >
          <h1>Monty Hall</h1>
        </Card>
        <Card >
          <NumberInput text='Quantas portas?' value={qtyDoors} onChange={newQty => setQtyDoors(newQty)}/>
        </Card>
        

      </div>
      <div>
      <Card >
      <NumberInput text='Porta com presente' value={gift} onChange={newGift => setGift(newGift)}/>
      </Card>
        <Card bgcolor="#28a085" >
          <Link href={`/game/${qtyDoors}/${gift}`} style={{textDecoration: 'none', cursor:'pointer'}}>
            <h2 style={{display:"flex", flex: "1",justifyContent:"center", alignContent:"center", margin:"0", color:"white" }} >
              Iniciar

            </h2>
          </Link>
        </Card>

      </div>

    </div>
    
  )
}
